### PR TITLE
Feature: Fetch weather based on current location

### PR DESCRIPTION
**Pull request by Luna-Jia**
- Update WeatherService to request location permission and handle denied cases
- Modify the weather button to trigger location permission request
- Display weather condition and temperature based on user's current location

issue #54

https://github.com/COSC481W-2024Winter/JARVIS/assets/73403516/7f0eb371-06f4-4971-8fc0-0a3430356605

### CODE REVIEW

**Comment by ghost** [comment]
image
problem in the test.

**Comment by haohuazheng3** [comment]
Try to fix the test that Emily mentioned and then make new pull request

**Comment by ghost** [comment]
several comments
there were numerous minor errors that I resolved with merge conflicts.
image

 however the application is not requesting permissions, so it can't get my location. Therefore the most important feature is to make sure it properly requests permissions.

**Comment by ghost** [comment]
fixed this error, by looking at the code you put your new code under the news button, but it should have been under the weather code. This allows for actually getting the users current location properly. @haohuazheng3 has further requested that there be some method to stop speech. His method is if you click the button again, then it stops. You can see this under his news button code. Please reopen the request when you have integrated this change

**Comment by haohuazheng3** [comment]
***Fetch the latest information from the main branch. Based on my _isSpeaking parameter and the solution in my News Summary(), resolve your part AI speaking bug. For example, clicking the first time will start reading, clicking again (second time) during the reading process will stop it, and clicking once more (third time) will restart the reading. You don't need to fix the bug where the reading continues even after exiting the software, as I have fixed that in home.dart. Also, Emily mentioned that she didn't see a permission request, which means that this feature seems to be directly obtaining the location without requesting permission from the user.

**Comment by ghost** [comment]
I already fixed the request, its just she put her new code under the news summary button instead of the weather button, everything is resolved except for the start/stop of sound.

**Comment by ghost** [comment]
looks good to me, stops and starts.

**Pull request merged**
